import { IsNotEmpty, IsString, ValidateNested } from 'class-validator';
import { Type, Transform } from 'class-transformer';

export class Review {
  id: number;

  @Transform(({ value }) => value.trim().substring(0, 150).toLocaleUpperCase())
  @IsNotEmpty({ message: 'landlord name must not be empty' })
  @IsString()
  landlord: string;

  @Transform(({ value }) => value.trim().substring(0, 150).toLocaleUpperCase())
  country_code: string;

  @Transform(({ value }) => value.trim().substring(0, 150).toLocaleUpperCase())
  @IsNotEmpty({ message: 'city must not be empty' })
  @IsString()
  city: string;

  @Transform(({ value }) => value.trim().substring(0, 150).toLocaleUpperCase())
  state: string;

  @Transform(({ value }) => value.trim().substring(0, 50).toLocaleUpperCase())
  @IsString()
  @IsNotEmpty({ message: 'zip must not be empty' })
  zip: string;

  review: string;
  repair: number;
  health: number;
  stability: number;
  privacy: number;
  respect: number;
  date_added: Date; // auto-generated by db
  flagged: boolean;
  flagged_reason: string;
  admin_approved: boolean | null;
  admin_edited: boolean;
}

export class CreateReviewDto {
  captchaToken: string;

  @ValidateNested()
  @Type(() => Review)
  review: Review;
}
