import { IsNotEmpty, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

export class Review {
  id: number;

  @IsNotEmpty({ message: 'landlord name must not be empty' })
  @IsString()
  landlord: string;

  country_code: string;

  @IsNotEmpty({ message: 'city must not be empty' })
  @IsString()
  city: string;

  state: string;
  zip: string;
  review: string;
  repair: number;
  health: number;
  stability: number;
  privacy: number;
  respect: number;
  date_added: Date; // auto-generated by db
  flagged: boolean;
  flagged_reason: string;
  admin_approved: boolean | null;
  admin_edited: boolean;
}

export class CreateReviewDto {
  captchaToken: string;

  @ValidateNested()
  @Type(() => Review)
  review: Review;
}
