export const resource_links = [
	{
		country: 'Canada',
		city: 'Toronto',
		name: "Toronto Tenants' Union",
		link: 'https://www.torontotenants.org/get_involved',
	},
	{
		country: 'Canada',
		city: 'Canada',
		name: 'ACORN Canada',
		link: 'https://acorncanada.org/acorn-tenant-unions/',
	},
	{
		country: 'Canada',
		city: 'Montreal',
		name: "Office municipal d'habitation de Montréal",
		link: 'https://www.omhm.qc.ca/en/community-life/actively-involved-tenants',
	},
	{
		country: 'Canada',
		city: 'Vancouver',
		name: 'Vancouver Tenants Union',
		link: 'https://www.vancouvertenantsunion.ca/',
	},
	{
		country: 'United States',
		city: 'United States',
		name: 'Guide to Tenants Unions in the US',
		link: 'https://abolitionnotes.org/a-quick-guide-to-all-tenants-unions-in-the-us',
	},
	{
		country: 'United States',
		city: 'New York',
		name: 'Tenants and Neighbors',
		link: 'https://www.tandn.org/',
	},
	{
		country: 'United States',
		city: 'Los Angeles',
		name: 'Los Angeles Tenants Union',
		link: 'https://latenantsunion.org/en/',
	},
	{
		country: 'United States',
		city: 'Chicago',
		name: 'Autonomous Tenants Union',
		link: 'https://www.autonomoustenantsunion.org/',
	},
	{
		country: 'United Kingdom',
		city: 'United Kingdom',
		name: 'ACORN the Union',
		link: 'https://acorntheunion.org.uk/',
	},
	{
		country: 'United Kingdom',
		city: 'London',
		name: 'London Renters Union',
		link: 'https://londonrentersunion.org/',
	},
	{
		country: 'United Kingdom',
		city: 'Birmingham',
		name: 'ACORN Birmingham',
		link: 'https://twitter.com/AcornBirmingham',
	},
	{
		country: 'United Kingdom',
		city: 'Liverpool',
		name: 'ACORN Liverpool',
		link: 'https://twitter.com/AcornLiverpool',
	},
	{
		country: 'Australia',
		city: 'Australia',
		name: 'Renters and Housing Union',
		link: 'https://rahu.org.au/join-rahu/',
	},
	{
		country: 'Australia',
		city: 'New South Wales',
		name: "New South Wales Tenants' Union",
		link: 'https://www.tenants.org.au/nato',
	},
	{
		country: 'New Zealand',
		city: 'Te Tōpū Tiaki-ā-Kainoho',
		name: 'Tenants Protection Association',
		link: 'https://www.tpa.org.nz/',
	},
	{
		country: 'New Zealand',
		city: 'Auckland',
		name: 'Tenants Protection Association',
		link: 'https://tpaauckland.org.nz/',
	},
]
