export interface Review {
  id: number;
  landlord: string;
  countryCode: string;
  city: string;
  state: string;
  zip: string;
  review: string;
  repair: number;
  health: number;
  stability: number;
  privacy: number;
  respect: number;
  dateAdded: Date; // auto-generated by db
}

//This will need to be updated to include a 'Flagged' boolean and a 'Flag Reason' string
