name: Request Review
on:
  pull_request:
    types:
      - opened

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: ankeetmaini/mandatory-reviews@v5
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          usernames: 'RateTheLandlordAdmin' # Add the usernames of the reviewers you want to add, separated by commas

