name: Merge Main Actions

on:
  pull_request:
    branches: ['main']

jobs:
  lint-be:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint backend
        run: |
          cd backend
          npm install
          npm run lint
  test-be:
    runs-on: ubuntu-latest
    needs: [lint-be]

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test frontend
        run: |
          cd backend
          npm install
          npm run test

  lint-fe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint frontend
        run: |
          cd frontend
          npm install
          npm run lint

  test-fe:
    runs-on: ubuntu-latest
    needs: [lint-fe]

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test frontend
        run: |
          cd frontend
          npm install
          npm run test-merge

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint-be, test-fe]

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create env file
        run: |
          touch .env
          echo BEPORT=${{secrets.BEPORT}} >> .env
          echo ENVIRONMENT=${{secrets.ENVIRONMENT}} >> .env
          echo FEPORT=${{secrets.FEPORT}} >> .env
          echo HCPATCHA_SECRET_KEY=${{secrets.HCPATCHA_SECRET_KEY}} >> .env
          echo HCPATCHA_SITE_KEY=${{secrets.HCPATCHA_SITE_KEY}} >> .env
          echo JWT_KEY="${{secrets.JWT_KEY}}" >> .env
          echo API_URL=${{secrets.API_URL}} >> .env
          echo NEXT_PUBLIC_HCPATCHA_SITE_KEY=${{secrets.NEXT_PUBLIC_HCPATCHA_SITE_KEY}} >> .env
          echo OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}} >> .env
          echo PGDATABASE=${{secrets.PGDATABASE}} >> .env
          echo PGHOST=${{secrets.PGHOST}} >> .env
          echo PGPASSWORD="${{secrets.PGPASSWORD}}" >> .env
          echo PGPORT=${{secrets.PGPORT}} >> .env
          echo PGUSERNAME=${{secrets.PGUSERNAME}} >> .env
          echo PGUSERNAME=${{secrets.PGUSERNAME}} >> .env
          echo UMUSERNAME=${{secrets.UMUSERNAME}} >> .env
          echo UMPASSWORD="${{secrets.UMPASSWORD}}" >> .env
          echo UMDATABASE=${{secrets.UMDATABASE}} >> .env
          echo DATABASE_URL="${{secrets.DATABASE_URL}}" >> .env
          echo NEXT_PUBLIC_FEATURE_FLAG_ID="${{secrets.NEXT_PUBLIC_FEATURE_FLAG_ID}}" >> .env
          cat .env
      - name: Pull Docker
        run: docker-compose pull
      - name: Build Docker
        run: docker-compose build