name: Merge Develop Actions

on:
  pull_request:
    branches: ['develop']

jobs:
  lint-be:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint backend
        run: |
          cd backend
          npm install
          npm run lint

  lint-fe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint frontend
        run: |
          cd frontend
          npm install
          npm run lint

  test-fe:
    runs-on: ubuntu-latest
    needs: [lint-fe]

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test frontend
        run: |
          cd frontend
          npm install
          npm run test-merge
